[tool.pyright]
include = ["./ReverseEngineering/", "./ProfileModification/"]

reportMissingImports = true
reportMissingTypeStubs = false

pythonVersion = "3.11"
pythonPlatform = "Linux"

executionEnvironments = [
  { root = "./ReverseEngineering/", pythonVersion = "3.11", extraPaths = [ "./Helpers/", "~/.local/share/pipx/venvs/mitmproxy/" ] },
  { root = "./ProfileModification/", pythonVersion = "3.11", extraPaths = [ "./Helpers/", "~/.local/share/pipx/venvs/mitmproxy/" ] },
]
